language: node_js
node_js: "12"
cache:
  yarn: true

addons:
  sonarqube:
    token:
      secure: $SONAR_TOKEN_CIKLUM

before_install:
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - yarn config set @ciklum-toggler:registry "https://registry.npmjs.org"

install:
  - yarn

script:
  - yarn ci:lint
  - yarn ci:test
  - yarn ci:build

before_deploy:
  - git checkout ${TRAVIS_BRANCH}
  - yarn config set @ciklum-toggler:registry "https://registry.npmjs.org"
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

deploy:
  provider: script
  script: yarn ci:publish
  skip_cleanup: true
  on:
    branch: master
